# Generated by Django 4.0.6 on 2022-08-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_org_alter_user_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='org',
            new_name='orgs',
        ),
    ]
