# Generated by Django 4.0.6 on 2022-08-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_orgrelationship'),
        ('user', '0004_rename_org_user_orgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='orgs',
        ),
        migrations.AddField(
            model_name='user',
            name='org_relationships',
            field=models.ManyToManyField(to='org.orgrelationship'),
        ),
    ]
