# Generated by Django 4.0.6 on 2022-08-10 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import org.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrelationship',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgrelationship',
            name='role',
            field=models.ForeignKey(default=org.models._get_role_id, on_delete=models.SET(org.models._get_role), related_name='relationship_set', related_query_name='relationship', to='org.orgrole'),
        ),
        migrations.AddField(
            model_name='orginvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orginvitation',
            name='invited_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orginvitation',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='org.org'),
        ),
    ]
