# Generated by Django 4.0.6 on 2022-08-04 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ['created_at'], 'permissions': (('manage_org', 'Can manage organization'),)},
        ),
        migrations.AlterModelOptions(
            name='orginvitation',
            options={'ordering': ['created_at'], 'permissions': (('manage_orginvitation', 'Can manage organization invitations'),)},
        ),
        migrations.AlterModelOptions(
            name='orgrole',
            options={'ordering': ['name'], 'permissions': (('manage_orgrole', 'Can manage organization roles of other users'),)},
        ),
        migrations.RemoveField(
            model_name='org',
            name='admin',
        ),
    ]
