# Generated by Django 4.0.6 on 2022-08-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_alter_org_options_alter_orginvitation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgrelationship',
            options={'ordering': ['created_at'], 'permissions': (('manage_orgrelationship', 'Can manage organization relationships of other users'),)},
        ),
        migrations.AlterModelOptions(
            name='orgrole',
            options={'ordering': ['name']},
        ),
    ]
