# Generated by Django 4.0.6 on 2022-08-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_alter_orgrelationship_options_alter_orgrole_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgrelationship',
            name='id',
            field=models.CharField(blank=True, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
