# Generated by Django 4.0.6 on 2022-08-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_alter_orgrelationship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgrelationship',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
