# Generated by Django 4.0.6 on 2022-08-08 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0007_alter_org_id_alter_orginvitation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='id',
            field=models.CharField(blank=True, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='id',
            field=models.CharField(blank=True, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
