# Generated by Django 4.0.6 on 2022-08-08 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0008_alter_org_id_alter_orginvitation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
