# Generated by Django 4.0.6 on 2022-08-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_orginvitation_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginvitation',
            name='revoked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
