# Generated by Django 4.0.6 on 2022-08-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_orgrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginvitation',
            name='relationship',
            field=models.CharField(choices=[('revoked', 'Revoked'), ('customer', 'Customer'), ('team', 'Team'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=256),
        ),
        migrations.AlterField(
            model_name='orgrelationship',
            name='relationship',
            field=models.CharField(choices=[('revoked', 'Revoked'), ('customer', 'Customer'), ('team', 'Team'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=256),
        ),
    ]
