# Generated by Django 4.0.6 on 2022-08-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('org', '0011_orginvitation_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrelationship',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions for the user of this relationship in this organization.', related_name='permissions', to='auth.permission'),
        ),
    ]
