# Generated by Django 4.0.6 on 2022-08-02 23:27

from django.db import migrations, models
import org.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('org', '0012_orgrelationship_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orginvitation',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='orgrelationship',
            name='relationship',
        ),
        migrations.AddField(
            model_name='orginvitation',
            name='role',
            field=models.CharField(choices=[('revoked', 'Revoked'), ('customer', 'Customer'), ('team', 'Team'), ('manager', 'Manager'), ('admin', 'Admin')], default='revoked', max_length=256),
        ),
        migrations.AlterField(
            model_name='orgrelationship',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions for the user of this relationship in this organization.', related_name='relationship_set', related_query_name='relationship', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('revoked', 'Revoked'), ('customer', 'Customer'), ('team', 'Team'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=256, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', org.models.OrgRoleManager()),
            ],
        ),
        migrations.AddField(
            model_name='orgrelationship',
            name='role',
            field=models.ForeignKey(default=org.models._get_role_id, on_delete=models.SET(org.models._get_role), related_name='relationship_set', related_query_name='relationship', to='org.orgrole'),
        ),
    ]
