# Generated by Django 4.0.6 on 2022-08-10 19:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dashboard', 'Dashboard'), ('fees', 'Fees'), ('financials', 'Financials'), ('governance', 'Governance'), ('integrations', 'Integrations'), ('payments', 'Payments'), ('reviews', 'Reviews'), ('taxes', 'Taxes'), ('ux', 'UX')], max_length=255), blank=True, null=True, size=None)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('for', 'For'), ('against', 'Against'), ('abstain', 'Abstain')], default='abstain', max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('released_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
