# Generated by Django 4.0.6 on 2022-08-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalvote',
            name='vote',
            field=models.CharField(choices=[(True, 'For'), (False, 'Against'), (None, 'Abstain')], default=None, max_length=255),
        ),
    ]
