# Generated by Django 4.0.6 on 2022-08-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_proposal_closed_at_alter_proposalvote_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='votes',
            field=models.ManyToManyField(blank=True, to='governance.proposalvote'),
        ),
    ]
