# Generated by Django 4.0.6 on 2022-08-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'permissions': (('manage_proposal', 'Can manage proposal'),)},
        ),
        migrations.AlterModelOptions(
            name='proposalvote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='approved',
        ),
        migrations.AddField(
            model_name='proposal',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
