# Generated by Django 4.0.6 on 2022-08-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_alter_proposal_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='votes',
            field=models.ManyToManyField(blank=True, null=True, to='governance.proposalvote'),
        ),
    ]
