# Generated by Django 4.0.6 on 2022-08-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_alter_proposal_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalvote',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
