# Generated by Django 4.0.6 on 2022-08-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_proposalvote_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
