# Generated by Django 4.0.6 on 2022-08-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0007_alter_proposalvote_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalvote',
            name='released_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='proposalvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
