# Generated by Django 4.0.6 on 2022-07-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(blank=True, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('draft', models.BooleanField(default=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.org')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
