# Generated by Django 4.0.6 on 2022-07-30 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_archived'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.schedule'),
        ),
    ]
