# Generated by Django 4.0.6 on 2022-08-08 04:19

from django.db import migrations, models
import utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(blank=True, default=utils.uuid.OrgIDMixin.id_generator, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
