# Generated by Django 4.0.6 on 2022-07-31 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_alter_org_id'),
        ('job', '0005_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org.org'),
        ),
    ]
