# Generated by Django 4.0.6 on 2022-08-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'ordering': ['-created_at'], 'permissions': (('manage_broadcast', 'Can manage broadcast'),)},
        ),
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'ordering': ['created_at'], 'permissions': (('manage_waitlistentry', 'Can manage waitlist entries'),)},
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='invite_id',
        ),
    ]
