# Generated by Django 4.0.6 on 2022-08-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
