# Generated by Django 4.0.6 on 2022-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_waitlistentry_accepted_at_alter_waitlistentry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
