# Generated by Django 4.0.6 on 2022-07-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
